#!/usr/bin/env sh
set -eu

# Upload iOS app
UPLOAD_PATH="gs://mobile.dev/cli_e2e"

zip -r -q SimpleWebViewApp.zip SimpleWebViewApp.app

gsutil cp SimpleWebViewApp.zip "$UPLOAD_PATH/SimpleWebViewApp.zip"
gsutil acl ch -r -u AllUsers:R "$UPLOAD_PATH/SimpleWebViewApp.zip"
